# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/dbg_ila/dbg_ila.xci
# IP: The module: 'dbg_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/dbg_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/dbg_ila/dbg_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/dbg_ila/dbg_ila.xci
# IP: The module: 'dbg_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/dbg_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/dbg_ila/dbg_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
