# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projects/srio_spi/srio_spi.cache/wt [current_project]
set_property parent.project_path C:/Projects/srio_spi/srio_spi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Projects/srio_spi/srio_spi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp
set_property used_in_implementation false [get_files C:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Projects/srio_spi/srio_spi.srcs/sources_1/new/spi_serdes.v
  C:/Projects/srio_spi/srio_spi.srcs/sources_1/new/spi_flash_programmer.v
  C:/Projects/srio_spi/srio_spi.srcs/sources_1/new/spi_loader_top.v
  C:/Projects/srio_spi/srio_spi.srcs/sources_1/new/top_project.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Projects/srio_test/srio_test/top.xdc
set_property used_in_implementation false [get_files C:/Projects/srio_test/srio_test/top.xdc]


synth_design -top top_project -part xc7k160tffg676-2


write_checkpoint -force -noxdef top_project.dcp

catch { report_utilization -file top_project_utilization_synth.rpt -pb top_project_utilization_synth.pb }
