# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_rx_inst/fifo_generator_rx_inst.xci
# IP: The module: 'fifo_generator_rx_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_rx_inst/fifo_generator_rx_inst/fifo_generator_rx_inst.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_rx_inst'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_rx_inst/fifo_generator_rx_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_rx_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_rx_inst/fifo_generator_rx_inst.xci
# IP: The module: 'fifo_generator_rx_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_rx_inst/fifo_generator_rx_inst/fifo_generator_rx_inst.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_rx_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/srio_spi/srio_spi.srcs/sources_1/ip/fifo_generator_rx_inst/fifo_generator_rx_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_rx_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
